Update Java Server Setup
MinecraftHopper/MinecraftHopper pull request #122
Opened 2021-08-17 22:33 UTC by elephant1214

There are a few things that need fixing which I added comments for, I can fix them tomorrow or someone else could now.

2021-08-18 07:54 UTC, Southpaw1496 commented
Please mark the request as draft until you've made all the changes you think are necessary.

2021-08-18 22:06 UTC, elephant1214 commented
> Please mark the request as draft until you've made all the changes you think are necessary.

2021-08-18 22:07 UTC, elephant1214 commented
Accidentally closed the pr, article is fixed

2021-08-23 11:51 UTC, Southpaw1496 requested changes
First review complete, I know a lot of them are stuff that you didn't change but if we're rewriting this we might as well go all the way.

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +* Make a new folder anywhere on your system. If you're using Windows, make sure your folder isn't in OneDrive. You can name the new folder anything you want, this will be our server folder or workspa
I think "isn't in the OneDrive folder" is more clear.
Also maybe change "this will be our server folder" to "this will be your server folder"

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +	* If you want your server to be on an older version, click to the version you want in the `Installations` tab in the launcher and click `SERVER` next to `VERSION`, it should open a new tab in your b
A screenshot or two might be helpful here, I think?

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +	* If you're looking to add plugins download [Paper](https://papermc.io/) instead
Perhaps "if you're looking to download Bukkit/Spigot plugins"

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +* Copy the *entire* name of the jar file you downloaded then go to [startmc](https://startmc.sh/) and paste your jar name in the `Server filename` field, be sure to add `.jar` to the end of pasted te
I think you should use the default recommended flags, there's no need to get fancy for a basic server. `java -Xmx1GM -Xms1G -jar minecraft_server.1.17.1.jar nogui` Also, encouraging people to use unofficial tools unnecessarily is something we want to avoid because A. We can't control what goes on in them and B. Doing it yourself gives you more of an understanding of how it works rather than having to rely on tools all the time. So just say something like "Copy this text, and replace "1G" with the amount of RAM you want to use in gigabytes"

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +* Go to the folder that contains your server, change the filetype to 'all' and name the file `start.bat` **There must to be a .bat at the end of the file name**,
Do they need to enable filename extensions in order to avoid naming the file `start.bat.txt` or whatever, or will it handle that?

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
>  * A computer to host it on. This guide has instructions specific to both Windows and MacOS, but a Linux machine should work as well. It is recommended to host a server on a desktop computer, but you
macOS is spelt with a small m.

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +* Open TextEdit and create a new document. If you see markdown tools at the top of the text document, press <strong>shift-cmd-t</strong> to hide them.
I think you mean "markup" or possibly "formatting" is the best word. Markdown is a specific formatting specification which TextEdit does not use.

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +* Copy the *entire* name of the jar file you downloaded then go to [startmc](https://startmc.sh/) and paste your jar name in the `Server filename` field, be sure to add `.jar` to the end of pasted te
See my above comment in the Windows section.

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +	* Should a message saying `Permission denied` appear, open a new terminal and run `chmod +x ` (space required), then drag your `start.command` (or `start.sh`) file into the terminal window, press 'e
I think the command is `chmod a+x` (or that's what I use anyway). This should go above the EULA agreement because permission will always be denied, macOS will never give a script file executable permissions by default as far as I know.

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
>  ## Eula {#eula}
Why is this in a separate section? I think a few repeated lines lines of text are worth the reduced confusion for users since it's required to start the server.

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
>  * A computer to host it on. This guide has instructions specific to both Windows and MacOS, but a Linux machine should work as well. It is recommended to host a server on a desktop computer, but you
I think there should be separate instructions for Linux, the macOS ones are far too specific to apply to Linux as well. Do it all via the terminal so that a person without GUI access can follow the guide as well.

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +* Now go to your workspace folder and double click the `start.command` (or `start.sh`) file to run it. You should see a terminal open. Once you've agreed to the [EULA](#eula), your server should star
The server will not start automatically once you agree to the EULA as far as I know, you need to restart it.

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +While using the vanilla server software, the best way to stop a server is to run `save-all` then `stop` once the world is saved to ensure the world is saved correctly. If for some reason you cannot u
Should be Ctrl-C, not Ctrl+C

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
>  ## The Server's Console {#console}
I don't **think** this section needs to be in a summary unless it has platform-specific information.

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
Might be good to change "Playing Multiplayer" to "Playing with others"

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +In order for them to join you, you will need to find your local IP. You can think of your IP as a join code or friend code used to access the server<br>
"In order for others to join you" perhaps?

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +There will be ads telling you to download files and programs, **do not click on them**.
Now I wonder who on earth thought we should send people to a site that makes us have to say this. (I know it wasn't you, Elephant :))

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +* Open command prompt and type 'ipconfig' then press 'enter' and look for:<br>
Add instructions for how to do this (e.g "Open Command Prompt (press start and type "Cmd")), perhaps?

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +Should your ISP not allow port forwarding, you can use a program like [ngrok](https://ngrok.com/) or [playit.gg](https://playit.gg/guides/minecraft/)
PlayIt seems more geared towards gaming, maybe we should only recommend one program?

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
192.168.1.254 is the UK's biggest provider's URL, maybe add that as well?

2021-08-23 11:51 UTC, Southpaw1496 commented on _help/setting-up-java-server/index.markdown
> +Now follow the OS specific instructions to setup the server. If you're using a linux server, follow the [MacOS instructions](#macos).
macOS is a small m

2022-04-07 22:47 UTC, Southpaw1496 commented
Author has lost interest in maintaining PR

2022-04-07 22:47 UTC, closed without merging