Improved and clearer Java installation tutorial with screenshots
MinecraftHopper/MinecraftHopper pull request #133
Opened 2022-02-21 10:15 UTC by lordofpipes

I spent some time making the tutorial for installing Java on par with the tutorial that we use for our server. It's now relevant to modern Minecraft with its new Java 17 requirements. It also avoids recommending Oracle JRE which could be a licensing trap for some users ever since the 2019 changes.

This also fixes the table formatting on the `Pixel Format Not Accelerated` article. Previously the tables were all squished together.

There's no license on this repository but feel free to consider this particular contribution as CC0 / public domain. Feel free to copy it verbatim to your website if you're a server or a hosting company.

Preview:

![whole-page](https://user-images.githubusercontent.com/68424788/154933232-afdd9c2f-28c3-4cfd-bddc-09d9b43168aa.png)
![windows](https://user-images.githubusercontent.com/68424788/154933240-6bba0ab9-3d09-4519-9bf2-8e012e2f993a.png)
![macos](https://user-images.githubusercontent.com/68424788/154933260-d9af6e6d-6f58-4927-bcba-da19bef9de72.png)
![linux](https://user-images.githubusercontent.com/68424788/154933285-1bb8544b-04a5-4b35-af3c-5b644c62c469.png)
![openjfx-multimc](https://user-images.githubusercontent.com/68424788/154933293-7c6ffae9-8e85-43d7-9463-0881f8dca793.png)

2022-02-21 10:20 UTC, randomairborne commented
This is perhaps a bit too comprehensive- almost feel like there should be links to the sections that will be needed the most, x86 Windows and Linux, or perhaps they should be at the top.

2022-02-21 10:29 UTC, lordofpipes commented
> This is perhaps a bit too comprehensive- almost feel like there should be links to the sections that will be needed the most, x86 Windows and Linux, or perhaps they should be at the top.

How about bringing "Possible symptoms of incorrect Java version" and "Verifying if Java is installed" to the bottom of the page and adding some anchor links to the top? The symptoms section is mainly for search engine accessibility anyways.

2022-02-21 10:34 UTC, lordofpipes commented
With a bit of Javascript, the quick links could also function to automatically open up the spoilers.

2022-02-21 13:14 UTC, Southpaw1496 requested changes
Hi

The changes I asked for are quite substantial, and I appreciate the work you've done that you'll now need to do over. To avoid this in future, you can either discuss this in a GitHub issue or on Discord (Discord will probably be more visible), or you can open draft pull requests as you work on contributions, so that we can see their progress and comment on them before they're done.

Also, since you're going to do most of your screenshots again, I'm going to tell you now that most of them are not very suitable. You've got too many markings and the screenshots are cluttered, especially in focused screenshots such as `adoptium-mac/openjdk-installer-2`. When markings are helpful, please use boxes where you can instead of circles and massive arrows (see: `adoptium-windows/openjdk-installer-4.jpg`).

Overall, though, the article is a well overdue rework, and I really appreciate the time that has gone into it :).

2022-02-21 22:26 UTC, lordofpipes commented on _help/installing-java/index.markdown
> +### I am on Windows and I need latest Java (Version 17) {#install-windows}
The original reason for the split is that I'm recommending Microsoft OpenJDK if you just need java 17, 64 bit, (the theory being that this is least chance of unexpected problems since it is an identical binary to what's used in Minecraft &mdash; has the same hash) and Adoptium if you need something older or 32 bit. This is not a great experience, because the Microsoft website is slightly harder to use because it does not auto detect platform for macOS, and of course *only* provides x64 and ARM.

If this article is to only recommend Adoptium, then yeah, this split is not necessary. I'll reorganize it accordingly.

2022-02-21 22:26 UTC, lordofpipes commented on _help/installing-java/index.markdown
> +**TL;DR: Most people running vanilla Minecraft with the default launcher will not need this tutorial!**
Some may arrive at this page via search engines &mdash; how about

> TL;DR: Most people running vanilla Minecraft with the default launcher will not need this tutorial, but if it has been suggested to you as a workaround, then continue.

2022-02-21 22:35 UTC, lordofpipes commented
> The changes I asked for are quite substantial, and I appreciate the work you've done that you'll now need to do over. To avoid this in future, you can either discuss this in a GitHub issue or on Discord (Discord will probably be more visible), or you can open draft pull requests as you work on contributions, so that we can see their progress and comment on them before they're done.

To be clear, this is a tutorial mostly adapted from what I use for another community, so I'm not miffed about the need for changes for it to be suitable for the Hopper, since I had already written most of it without Hopper in mind. I'll work on these points, ty for the feedback.

2022-02-22 04:35 UTC, lordofpipes commented on _help/installing-java/index.markdown
> +### I am on Windows and I need latest Java (Version 17) {#install-windows}
Done.

2022-02-22 04:42 UTC, lordofpipes commented
I have switched the tutorial to Adoptium-only and did all these changes you suggested. Changed all of the ellipses to rectangles and only used markings where it might be non-obvious.

Preview of the page on first load:

![everything-collapsed](https://user-images.githubusercontent.com/68424788/155064170-0d667a4e-f5e5-4c1c-acb8-ededbec0fef5.png)

Preview of the page after expanding the spoilers:

![everything-expanded](https://user-images.githubusercontent.com/68424788/155064328-5e69c361-8ce7-4958-bc45-18022014bc0b.jpg)

2022-02-22 13:26 UTC, Southpaw1496 requested changes
Review 2, ~~Electric Boogaloo~~

Feel free to reply to my comments or ping me on Discord with any questions :)

2022-02-22 13:26 UTC, Southpaw1496 commented on _help/installing-java/index.markdown
> +Once you have installed the proper Java version, you should configure this in your launcher and give the game a go! Depending on your launcher you may need to manually navigate to the path of Adoptiu
We actually have an article on this, https://minecrafthopper.net/help/guides/changing-java-version/

It's very, very outdated though, so I will work on updating it myself, and it can be merged before this article.

We don't need to deal with 3rd-party launchers either, you can get rid of this entire section.

2022-02-22 13:26 UTC, Southpaw1496 commented on _help/installing-java/index.markdown
> +You can check which version of Java may be already installed on your computer by following these instructions.
```suggestion
You can check if a version of Java is already installed on your computer by following these instructions.
```

2022-02-22 13:26 UTC, Southpaw1496 commented on _help/installing-java/index.markdown
> +(When attempting to launch with MultiMC)
We're not dealing with 3rd-party launchers or server software, all of this can go.

Forge can stay, I think, because of its ubiquitousness with normal people (as opposed to enthusiasts or server admins).

2022-02-22 13:26 UTC, Southpaw1496 commented on _help/installing-java/index.markdown
> +```
All of this can go, non-Minecraft things (even if they're Minecraft related) are out of scope for this article.

2022-02-22 13:26 UTC, Southpaw1496 commented on _help/installing-java/index.markdown
> +Choose the appropriate version, and click **Latest release** to start the download. Note that Temurin versions are the same as Java versions, so "Temurin 17" means "Temurin Java 17". See the above ch
You need to expand this section to explain how to get older versions of Java/OpenJDK.

2022-02-22 13:26 UTC, Southpaw1496 commented on _help/installing-java/index.markdown
> +The below compatibility chart was last updated 2022-02-20.
Get rid of the EOL links on the table, they're confusing for the average person. I'd recommend adding something above the update notice instead, like so:
```suggestion
**Note:** Java versions 6, 8, and 16 no longer receive security updates, and are therefore more risky to use. You should use Java 11 or 17 if you can, as they will receive security updates for years to come.

The below compatibility chart was last updated 2022-02-20.
```
Java 8 EOLs on March 31st, so I also added that to the note.

2022-02-22 23:25 UTC, lordofpipes commented on _help/installing-java/index.markdown
> +If your distro does not support Java, the Microsoft OpenJDK or Adoptium downloads can be used on all distros.
Distributions and package managers are roughly the same thing, but yeah that might be clearer

2022-02-22 23:32 UTC, lordofpipes commented on _help/installing-java/index.markdown
> +(When attempting to launch with MultiMC)
Hmm, I'm disappointed this won't be considered in-scope since excluding it limits the usefulness of the article, and excluding the symptoms limits search engine visibility of the article. Most people are installing Java manually because they're trying to get third-party tools or server software working, since if they were using vanilla it would already be handled

2022-02-23 08:45 UTC, Southpaw1496 commented on _help/installing-java/index.markdown
> +(When attempting to launch with MultiMC)
I think that, first and foremost, this site is a tool for MCCS. In general, we only support official things, and while I agree that including additional information about 3rd-party launchers would increase its usefulness outside of supporting official things, it would just increase confusion for users not trying to use those tools, and therefore make it less useful for us specifically.

2022-02-23 08:50 UTC, Southpaw1496 commented on _help/installing-java/index.markdown
> +(When attempting to launch with MultiMC)
On top of this, we shouldn't be "supporting" (for want of a better term) 3rd-party tools on the site that we won't support on Discord, that's inconsistent.

2022-02-23 09:28 UTC, Southpaw1496 commented on _help/installing-java/index.markdown
> +If your distro does not support Java, the Microsoft OpenJDK or Adoptium downloads can be used on all distros.
Aren't distributions different versions, like Ubuntu, Fedora, Debian etc.

2022-02-24 00:18 UTC, lordofpipes commented
> Are you ready for another review or do you still have work to do?

Go for it

2022-02-25 17:06 UTC, Southpaw1496 requested changes
Review 3

If there's anything you are unsure of/disagree with, feel free to discuss it with me before commiting anything :)

2022-02-25 17:06 UTC, Southpaw1496 commented on _help/installing-java/index.markdown
> +## Verifying if Java is installed {#verifying}
Move this above the tutorial section.

2022-02-26 00:53 UTC, lordofpipes commented
Looks good, I've done all these changes, fixed a few typos. Thank you!

2022-03-02 08:05 UTC, Southpaw1496 requested changes
Looks excellent, just one more thing that I noticed

2022-03-02 08:05 UTC, Southpaw1496 commented on _help/installing-java/index.markdown
> +- [Do I need Java? Which version do I need?](#which-java)
You need to change this to reflect the new order of the sections.

2022-03-02 17:53 UTC, lordofpipes commented
Fixed

2022-03-04 07:38 UTC, Southpaw1496 requested changes
We're getting so close!

2022-03-04 07:38 UTC, Southpaw1496 commented on _help/installing-java/index.markdown
> +**Additional info:** [Verifying if Java is installed properly](#verifying)
Move this above the Changing launcher. They should verify they have installed Java correctly before trying to use it for anything.

2022-03-05 22:11 UTC, Southpaw1496 approved these changes

2022-06-06 00:51 UTC, lordofpipes commented
#136 was merged so I went ahead and added platform detection to this new tutorial to keep the pull request up to date - fffa87e

2022-06-27 00:05 UTC, LordRalex approved these changes

2022-06-27 00:05 UTC, merged