Clarify wording for error conditions
MinecraftHopper/MinecraftHopper pull request #139
Opened 2022-06-19 00:43 UTC by randomairborne

very basic wording cleanup. Confused a few people.

2022-06-19 15:56 UTC, Greymagic27 requested changes

2022-06-19 15:56 UTC, Greymagic27 commented on _help/guides/getting-minecraft-launcher-log/index.md
> +Start the launcher and use it to the point where the error occurs. Then close Minecraft and keep it closed.
I don't think this is clearer. It's stating now to load up the launcher, to "use" it, and then close Minecraft when the error occurs. My issue with this is that the user is just being told to load up the launcher, not being told to launch the game until a crash occurs.

I think the old wording is actually better

2022-06-19 16:12 UTC, randomairborne commented on _help/guides/getting-minecraft-launcher-log/index.md
> +Start the launcher and use it to the point where the error occurs. Then close Minecraft and keep it closed.
Not all errors that warrant a launcher log are game crashes, though.

2022-06-19 16:13 UTC, Greymagic27 commented on _help/guides/getting-minecraft-launcher-log/index.md
> +Start the launcher and use it to the point where the error occurs. Then close Minecraft and keep it closed.
But then that leaves the question that will the user understand that they need to load up the game for game crashes, if it just says to load up the launcher

2022-06-19 16:14 UTC, randomairborne commented on _help/guides/getting-minecraft-launcher-log/index.md
> +Start the launcher and use it to the point where the error occurs. Then close Minecraft and keep it closed.
hmm. this may need bikeshedding

2022-06-20 00:55 UTC, duendwang commented on _help/guides/getting-minecraft-launcher-log/index.md
> +Start the launcher and use it to the point where the error occurs. Then close Minecraft and keep it closed.
I replied with a comment but it didn't get sent.

Perhaps "Try to start Minecraft and ..."

2022-06-27 00:07 UTC, closed without merging

2022-10-11 08:00 UTC, duendwang commented
Better wording would be "try to start minecraft...."

On Sun, Jun 19, 2022, 09:14 valkyrie_pilot ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In _help/guides/getting-minecraft-launcher-log/index.md
> <https://github.com/MinecraftHopper/MinecraftHopper/pull/139#discussion_r901128713>
> :
>
> > @@ -21,7 +21,7 @@ The launcher log contains history from when the launder is started up until the
>
>  #### Step 1
>
> -Start Minecraft and run it to the point where the crash/error occurs. Then close Minecraft and keep it closed.
> +Start the launcher and use it to the point where the error occurs. Then close Minecraft and keep it closed.
>
> hmm. this may need bikeshedding
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MinecraftHopper/MinecraftHopper/pull/139#discussion_r901128713>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABZJLBFEFLPHFBHWDNAMCXLVP5BP3ANCNFSM5ZFROOOA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***
> com>
>