Add favicon
MinecraftHopper/MinecraftHopper pull request #141
Opened 2022-07-07 23:11 UTC by SmallPepperZ

A successor to #113.
- Adds the hopper minecart icon as a favicon
- Adds image files for Android and IOS home screen and Windows start menu icons
- Adds opengraph tags to show the icon in Discord embeds

2022-07-08 10:27 UTC, urielsalis approved these changes

2022-07-09 10:21 UTC, Greymagic27 approved these changes

2022-07-09 10:27 UTC, Southpaw1496 requested changes

2022-07-09 10:27 UTC, Southpaw1496 commented on _layouts/default.html
> +  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
From my testing, `apple-touch-icon` is no longer actually used in modern versions of Safari.

2022-07-09 10:27 UTC, Southpaw1496 commented on _layouts/default.html
> +  {% seo %}
How is adding SEO related to favicons?

2022-07-09 16:03 UTC, SmallPepperZ commented on _layouts/default.html
> +  {% seo %}
That wasn't something I added, it shows up that way because I fixed the indentation for the head section

2022-07-09 16:05 UTC, SmallPepperZ commented on _layouts/default.html
> +  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
Apple touch icon is for adding a site bookmark to the home screen. It worked for me in my testing on iOS 15.5

2022-07-09 16:08 UTC, LordRalex approved these changes

2022-07-09 16:08 UTC, Southpaw1496 commented on _layouts/default.html
> +  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
That can use the standard favicon, if you try on https://quiltmc.org, which does not have an apple-touch-icon, it works fine.

2022-07-09 16:09 UTC, merged