Update factoids.json
MinecraftHopper/MinecraftHopper pull request #170
Opened 2024-10-24 02:18 UTC by duendwang

Modified maincord ban factoid (discord/ban) to include the appeals form link while keeping the original text explaining that we are not associated and cannot help with appeals.

2024-10-24 02:55 UTC, LordRalex commented
Here is my concern with it. It's been changed several times. It's been through 4 different methods, with no indication it's actually changed. 

I am tired of having to change it. 

I don't think it's our place to really direct them.

Is this URL already public in some way that we are not the only ones who share it out?

2024-10-24 03:17 UTC, duendwang commented
I don't really care if the factoid is changed again or not, but it saves
having to dig out the link for those that want to respond to these
requests.

I think it's here to stay, but of course, it still could change.
The link isn't publicized like Twitter was, but it's definitely out there.
This method's been in place for about a year now if I recall correctly.


On Wed, Oct 23, 2024, 19:55 Joshua Taylor ***@***.***> wrote:

> Here is my concern with it. It's been changed several times. It's been
> through 4 different methods, with no indication it's actually changed.
>
> I am tired of having to change it.
>
> I don't think it's our place to really direct them.
>
> Is this URL already public in some way that we are not the only ones who
> share it out?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MinecraftHopper/MinecraftHopper/pull/170#issuecomment-2434135852>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABZJLBDC3IWB4CW2IG7QCKTZ5BOSDAVCNFSM6AAAAABQQBNUTSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZUGEZTKOBVGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-29 18:37 UTC, LordRalex requested changes

2024-10-29 18:37 UTC, LordRalex commented on factoids.json
> +        "content": "To appeal your ban from the official Minecraft Discord servers, log in with the banned account at the following site and fill out the ban appeals form: <https://dyno.gg/form/f4871
"ban appeals form" should be "ban appeal form"

2024-10-29 19:02 UTC, merged