Add error codes
MinecraftHopper/MinecraftHopper pull request #26
Opened 2020-09-03 21:52 UTC by superpowers04

Creating this pull request so I don't forget, Not finished yet

2020-09-05 18:22 UTC, superpowers04 commented
Pull request now should be good to go

2020-09-06 18:35 UTC, LordRalex requested changes

2020-09-06 18:35 UTC, LordRalex commented on _help/exit-code/code-1073740777/index.markdown
> +## Windows Vista
Remove Vista and XP. They are not supported.

2020-09-06 18:35 UTC, LordRalex commented on _help/exit-code/code-1073740777/index.markdown
> +## Windows 7 / 8
We also need Windows 10.

2020-09-06 18:35 UTC, LordRalex commented on _help/exit-code/code-1073741819/index.markdown
> +
Remove the extra lines here.

2020-09-06 18:35 UTC, LordRalex commented on _help/exit-code/code-1073741819/index.markdown
> +* This may possibly be caused by having D3Dgear installed. (If that is the case, please let us know!)
Link the D3DGear page.

2020-09-06 18:35 UTC, LordRalex commented on _help/exit-code/code-2147483645/index.markdown
> +[You can find info on how to reinstall java here](http://localhost:4000/help/how-to-reinstall-java/)
This is a bad link.

2020-09-06 18:35 UTC, LordRalex commented on _help/exit-code/index.markdown
> +                <a href="/MinecraftHopper/help/exit-code/code-139/">139</a>
All the URLS here are wrong, they should not have MinecraftHopper in them.

2020-09-06 18:35 UTC, LordRalex commented on _help/failed-check-session-lock/index.markdown
> +title:  "Exit code 139"
You changed this page by accident.

2020-09-06 18:35 UTC, LordRalex commented on _layouts/default.html
> +        <a href="/" class="muted"><h3>MinecraftHopper</h3></a>Get community help for Minecraft
Revert these changes, this file is okay as-is.

2020-09-08 17:42 UTC, LordRalex commented on _help/exit-code/code-1073741819/index.markdown
> +* This may possibly be caused by having D3Dgear installed. (If that is the case, please let us know!)
I had meant the removal page, not the main site. (exit code 1073740777)

2020-09-08 17:42 UTC, LordRalex commented on _help/exit-code/index.markdown
> +Exit statuses are also OS-dependent integers unless set by Minecraft or a another loaded library.
"a another"

2020-09-08 19:25 UTC, superpowers04 commented on _help/exit-code/index.markdown
> +Exit statuses are also OS-dependent integers unless set by Minecraft or a another loaded library.
I never put that :thinking:

2020-09-14 18:33 UTC, merged