Changes to mods articles
MinecraftHopper/MinecraftHopper pull request #45
Opened 2021-01-02 11:06 UTC by Southpaw1496

In short:
- There is now an `installing-mods` folder and article with links to mod loader install guides in the `guides` folder
- `Installing-forge is now called forge and is located in the aforementioned `installing-mods` folder
- Accompanying it is a guide on how to install Fabric mods.
- I also made a slight tweak to the Forge guide explaining how to right-click the installer and click Open in order to bypass macOS's Gatekeeper protection if you're using macOS
- And finally I modified the Forge article description to be more, well, descriptive

2021-01-02 15:29 UTC, LordRalex requested changes

2021-01-02 15:29 UTC, LordRalex commented on _help/guides/installing-mods/fabric/index.markdown
> +Fabric is a mod loader for Minecraft. It updates much faster than Forge which makes it popular for smaller, more technical mods, such as Carpet, Sodium, or the Replay Mod. In this tutorial, we will b
The argument that forge vs fabric is faster is a bit... misleading. Forge updates fast as well, it's only in a few scenarios when Forge *rewrote an entire toolchain* that it took longer. Let's not put that forge is slower.

2021-01-02 15:29 UTC, LordRalex commented on _help/guides/installing-mods/fabric/index.markdown
> +Double-click the downloaded JAR file and accept click "OK" when the prompt appears. If nothing happens, try installing and running [JarFix](https://johann.loefflmann.net/downloads/jarfix.exe)
It may not work because Java is not installed.

2021-01-02 15:29 UTC, LordRalex commented on _help/guides/installing-mods/index.markdown
> +Mods are pieces of code (usually in JAR files) which change the way the game works.
I'd like to expand this. We need to discuss the "safest" places to get mods, along with things to be careful of, i.e mods are not made by Mojang and as such, can contain content that is not appropriate for children.

2021-01-02 15:29 UTC, LordRalex commented on _help/guides/installing-mods/index.markdown
> +[Installing Forge](/_help/guides/installing-mods/forge/index.markdown) (Most modpacks and pre-1.14 mods)
This version statement is odd. Also your link should not need index.markdown in it

2021-01-02 19:23 UTC, Southpaw1496 commented on _help/guides/installing-mods/index.markdown
> +[Installing Forge](/_help/guides/installing-mods/forge/index.markdown) (Most modpacks and pre-1.14 mods)
Made some changes in the latest commit, see what you think

2021-01-02 19:37 UTC, LordRalex commented on _help/guides/installing-mods/index.markdown
> +[Installing Forge](/_help/guides/installing-mods/forge/index.markdown) (Most modpacks and pre-1.14 mods)
You did not push your changes

2021-01-02 21:49 UTC, Southpaw1496 commented on _help/guides/installing-mods/index.markdown
> +[Installing Forge](/_help/guides/installing-mods/forge/index.markdown) (Most modpacks and pre-1.14 mods)
🤦 my bad, should be there now

2021-01-02 22:12 UTC, LordRalex requested changes

2021-01-02 22:12 UTC, LordRalex commented on _help/guides/installing-mods/index.markdown
> +Mods are pieces of code (usually in JAR files) which change the way the game works. Mods are not created or regulated by Mojang, so some of them may contain malicious code or explicit content. One of
"they do not fully review all the mods on the site"

They do....

2021-01-02 22:15 UTC, Southpaw1496 commented on _help/guides/installing-mods/index.markdown
> +Mods are pieces of code (usually in JAR files) which change the way the game works. Mods are not created or regulated by Mojang, so some of them may contain malicious code or explicit content. One of
I was not aware of this.
All fixed

2021-01-25 21:35 UTC, LordRalex requested changes
Java fix

2021-02-06 16:19 UTC, LordRalex approved these changes

2021-02-06 16:19 UTC, merged