David
MinecraftHopper/MinecraftHopper pull request #52
Opened 2021-01-22 00:35 UTC by duendwang

Created articles for hosts file fix and troubleshooting login issues.

2021-01-22 01:29 UTC, duendwang commented
Did I do this correctly?

Also I just remembered that the mac and Linux screenshots are missing for the hosts file fix page. Let me know if you want to merge first and then PR again with the screenshots, or wait until those screenshots are in.

2021-01-24 08:58 UTC, duendwang commented
Added linux and mac screenshots to hosts file guide.
Redid numbering formatting in tables to be cleaner and converted markdown formatting to HTML inside tables.

2021-01-25 16:45 UTC, LordRalex requested changes

2021-01-25 16:45 UTC, LordRalex commented on _help/cannot-log-in/index.markdown
> +If you are still not able to log in, but can log in on other devices. You can join the [Minecraft Support Discord](https://discord.gg/58Sxm23) for further help and troubleshooting. As with any online
I think we have a page for technical resourrces, would prefer that page to be used.

2021-01-25 16:45 UTC, LordRalex commented on _help/hosts-file/index.markdown
> +    <td><img src="https://cdn.discordapp.com/attachments/607129205981052929/801902607203172392/unknown.png" height=200></td>
Upload the images to the repo instead of using it from Discord

2021-01-25 20:11 UTC, LordRalex approved these changes

2021-01-25 20:12 UTC, merged