remove malware (mac addition needed)
MinecraftHopper/MinecraftHopper pull request #60
Opened 2021-01-30 20:33 UTC by randomairborne

antivirus for win only is better then antivirus for none at all

2021-02-06 02:17 UTC, TechnoShip123 submitted a review, later dismissed
Content is accurate

2021-02-06 16:25 UTC, LordRalex requested changes

2021-02-06 16:25 UTC, LordRalex commented on _help/removing-malware/index.markdown
> +Some malware can interfere with minecraft and its RAM allocation, causing crashes and login issues.  Malwarebytes ADWcleaner needs to be used as it is known to be safe, effective, and not interfere w
Minecraft. And RAM allocation doesn't matter in most cases. That's only specific to 1 program, which isn't "malware".
I don't like how the second sentence is worded here either.

2021-02-06 16:25 UTC, LordRalex commented on _help/removing-malware/index.markdown
> +title:  "ADWcleaner and Malwarebytes"
The tool is called AdwCleaner. Please fix this across the board.

2021-02-06 17:03 UTC, randomairborne commented on _help/removing-malware/index.markdown
> +Some malware can interfere with minecraft and its RAM allocation, causing crashes and login issues.  Malwarebytes ADWcleaner needs to be used as it is known to be safe, effective, and not interfere w
I dont truly understand why it interferes with minecraft, this is what I understood from what I could.  enlightenment is appreciated

2021-02-06 17:08 UTC, randomairborne commented on _help/removing-malware/index.markdown
> +title:  "ADWcleaner and Malwarebytes"
Done.

2021-02-13 21:26 UTC, LordRalex approved these changes

2021-02-13 21:27 UTC, merged