AMD Default GPU
MinecraftHopper/MinecraftHopper pull request #62
Opened 2021-02-06 02:11 UTC by TechnoShip123

I've added resources and a markdown file in their respective locations for setting the default GPU on AMD graphics cards. @duendwang can you pull this into the repository? I've also matched it with the directory structure.

2021-02-06 02:56 UTC, TechnoShip123 commented
Forgot to delete the `deleteme` files, they were temporary so that I could create directories that matched master's dir format. I'll fix it asap.

2021-02-06 16:28 UTC, LordRalex requested changes

2021-02-06 16:28 UTC, LordRalex commented on _help/amd-dedicated-gpu/dedicated_gpu.md
> +# How to Switch Between Graphics Card and iGPU with AMD
This is missing the default header that other pages have.

2021-02-06 16:28 UTC, LordRalex commented on _help/amd-dedicated-gpu/dedicated_gpu.md
> +Some computers have a processor that also contains its own GPU, commonly known as the **iGPU** (Integrated Graphics Processing Unit). While it functions like most GPUs, it isn't as strong as most gra
Nvidia has the same issue. Any reason why it's not included here, and why this page is a generic question, but it's specific to a solution.

2021-02-06 16:28 UTC, LordRalex commented on static/images/help/amd-dedicated-gpu/deleteme.txt
> +e
Yes, delete this.

2021-02-06 16:28 UTC, LordRalex commented on _help/amd-dedicated-gpu/dedicated_gpu.md
> +**TIP:** For even *better* performance, make sure to consider mods such as [Sodium](http://www.curseforge.com/minecraft/mc-mods/sodium) and [Optifine](http://optifine.net/home)!
I am not a fan of recommending 3rd party content here, especially with the issues they can cause. This is an unrelated help that I would prefer we not include on this page.

2021-02-06 17:46 UTC, TechnoShip123 commented on _help/amd-dedicated-gpu/dedicated_gpu.md
> +Some computers have a processor that also contains its own GPU, commonly known as the **iGPU** (Integrated Graphics Processing Unit). While it functions like most GPUs, it isn't as strong as most gra
@LordRalex I'm not exactly sure what you meant by this, does [this commit](https://github.com/TechnoShip123/MinecraftHopper/commit/09c1da21e0485487fbdedfc8e7fa8a221c3e75b3) solve what you said?

2021-02-13 21:28 UTC, LordRalex approved these changes

2021-02-13 21:28 UTC, merged